# Generated by Django 3.2.8 on 2021-10-21 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0003_remove_post_comment_count'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author',
            name='profile_picture',
            field=models.ImageField(default='static_in_env/img/user.jpg', upload_to=''),
        ),
    ]
